### ISSUE TITLE
Sip are calculated Wrong

### ISSUE THREAD

**Issue by ThePepsi** [ThePepsi/BusBot#18]
nd los Geht es! Karten werden ausgeteilt! 
 Wenn jeder seine Karten hat bitte :arrows_counterclockwise: drücken. 
 Mittspieler sind:
:sunglasses: => ThePepsi#1583
:grinning: => Erebos_Uni#1561
Die Neue Karte ist: [G7]
Das ist die Pyramide:
XX 
XX XX 
XX XX XX 
XX XX XX G7
@ThePepsi : Darf 1 verteilen, bitte wähle einen Spieler zum Drinken.
@Erebos_Uni : Darf 1 TRINKEN, bedank dich bei ThePepsi#1583
Die Neue Karte ist: [SK]
Das ist die Pyramide:
XX 
XX XX 
XX XX XX 
XX XX SK G7
Die Neue Karte ist: [EO]
Das ist die Pyramide:
XX 
XX XX 
XX XX XX 
XX EO SK G7
Die Neue Karte ist: [SO]
Das ist die Pyramide:
XX 
XX XX 
XX XX XX 
SO EO SK G7
Die Neue Karte ist: [H8]
Das ist die Pyramide:
XX 
XX XX 
XX XX H8 
SO EO SK G7
Die Neue Karte ist: [S8]
Das ist die Pyramide:
XX 
XX XX 
XX S8 H8 
SO EO SK G7
Die Neue Karte ist: [G8]
Das ist die Pyramide:
XX 
XX XX 
G8 S8 H8 
SO EO SK G7
Die Neue Karte ist: [HU]
Das ist die Pyramide:
XX 
XX HU 
G8 S8 H8 
SO EO SK G7
Die Neue Karte ist: [E9]
Das ist die Pyramide:
XX 
E9 HU 
G8 S8 H8 
SO EO SK G7
@Erebos_Uni : Darf 4 verteilen, bitte wähle einen Spieler zum Drinken.
@ThePepsi : Darf 4 TRINKEN, bedank dich bei Erebos_Uni#1561

**Comment by ThePepsi** [comment]
IS: Darf 4 verteilen
Soll: Darf 3 verteilen

**Comment by JohannHeinel** [comment]
fixed the sip count
